# define the build steps
steps:
  # install the app dependencies
  - name: 'gcr.io/cloud-builders/npm'
    args: ['install']

  - name: 'gcr.io/cloud-builders/npm'
    args: ['run', 'create-env']
    env:
    - 'DB_CONNECT=${_SECRET_KEY}'
    - 'DB_VAR=${_MY_VAR}'
    - 'DB_CONNECT2=DB_CONNECT2'

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
    - '-eEuo'
    - 'pipefail'
    - '-c'
    - |-
      SECRET_NAME="CARTWIRE_BIN_PROD_DATABASE"
      PROJECT_ID="exploring-gcp-373314"

      # retrieve the secret value
      SECRET_VALUE=$(gcloud secrets versions access latest --secret="$SECRET_NAME" --project="$PROJECT_ID")

      # store the secret value in an environment variable
      export MY_SECRET="$SECRET_VALUE"
  # execute the tests
#  - name: 'gcr.io/cloud-builders/npm'
#    args: ['run', 'test'] 

  # build an artifact using the docker builder
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/exploring-gcp-373314/github_devashish-s_cartwire-bin:latest', '.']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/exploring-gcp-373314/github_devashish-s_cartwire-bin']

# deploy container image to GKE
  - name: 'gcr.io/cloud-builders/gke-deploy'
    args:
    - run
    - --filename=kubernetes.yaml
    - --image=gcr.io/exploring-gcp-373314/github_devashish-s_cartwire-bin
    - --location=us-central1-a
    - --cluster=nginx-1-cluster
  
images:
  - 'gcr.io/exploring-gcp-373314/github_devashish-s_cartwire-bin:latest'