# define the build steps
steps:
  # install the app dependencies
  - name: 'gcr.io/cloud-builders/npm'
    args: ['install']

  - name: 'gcr.io/cloud-builders/npm'
    args: ['run', 'create-env']
    env:
    - 'DB_CONNECT=${_SECRET_KEY}'
    - 'DB_VAR=${_MY_VAR}'
    - 'DB_CONNECT2=DB_CONNECT2'

  - name: bash
    script: |
      #!/usr/bin/env bash
      export SECRET_VALUE=$(gcloud secrets versions access latest --secret="CARTWIRE_BIN_PROD_DATABASE" --project="exploring-gcp-373314")

  - name: 'bash'
    args: ['echo', 'gcloud secrets versions access latest --secret="CARTWIRE_BIN_PROD_DATABASE" --project="exploring-gcp-373314"']

  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args: ['bash.sh','--foo']
  # execute the tests
#  - name: 'gcr.io/cloud-builders/npm'
#    args: ['run', 'test'] 

  # build an artifact using the docker builder
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/exploring-gcp-373314/github_devashish-s_cartwire-bin:latest', '--build-arg=ENV=$_MY_VARIABLE', '.']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/exploring-gcp-373314/github_devashish-s_cartwire-bin']


  - name: 'gcr.io/cloud-builders/bash'
    args:
      - -c
      - |
        export MY_SECRET=$(gcloud secrets versions access latest --secret="CARTWIRE_BIN_PROD_DATABASE" --project="exploring-gcp-373314")

# deploy container image to GKE
  - name: 'gcr.io/cloud-builders/gke-deploy'
    args:
    - run
    - --filename=kubernetes.yaml
    - --image=gcr.io/exploring-gcp-373314/github_devashish-s_cartwire-bin
    - --location=us-central1-a
    - --cluster=nginx-1-cluster
images:
  - 'gcr.io/exploring-gcp-373314/github_devashish-s_cartwire-bin:latest'
timeout: 1200s