apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: dev-secret-store
  namespace: dev
spec:
  provider:
    gcpsm:  
      projectID: exploring-gcp-373314
      auth:
        workloadIdentity:
          clusterLocation: us-central1-c
          clusterName: cartwire-bin-cluster
          serviceAccountRef:
            name:  workload-identity-ksa

---
 
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: externalsecret
  namespace: dev
spec:
  refreshInterval: 1m           
  secretStoreRef:
    kind: SecretStore
    name: dev-secret-store              
  target:
    name: workload-secret  
    creationPolicy: Owner
  data:
  - secretKey: k8s-secret-key-testsecret  
    remoteRef:
      key: CARTWIRE_BIN_PROD_DATABASE

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dev-ingress
  namespace: dev
  annotations:
    ingress.kubernetes.io/enable-cors: "true"
    ingress.kubernetes.io/cors-allow-origin: "http://localhost/"
    ingress.kubernetes.io/cors-allow-methods: "GET, POST, PUT, DELETE, OPTIONS" 
#    ingress.kubernetes.io/cors-allow-headers: "Authorization, Content-Type" http://localhost/cors-test.html
spec:
  rules:
  - http:
      paths:
      - path: /*
        pathType: Prefix
        backend:
          service:
            name: dev-service
            port:
              name: http

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: cartwirebinapp
#  namespace: default
  namespace: dev
  labels:
    app: cartwirebinapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cartwirebinapp
  template:
    metadata:
      labels:
        app: cartwirebinapp
    spec:
      containers:
      - name: cartwirebinapp
        image: gcr.io/exploring-gcp-373314/github_devashish-s_cartwire-bin:latest
        imagePullPolicy: Always
#        env:
#        - name: BERGLAS_SECRET
#          value: $(gcloud secrets versions access latest --secret="CARTWIRE_BIN_PROD_DATABASE" --project="exploring-gcp-373314")
        env:
        - name: WORKLOAD_SA
          valueFrom:
            secretKeyRef:
              name: workload-secret
              key: k8s-secret-key-testsecret
