apiVersion: "cartwire-bin-app/v1"
kind: "Deployment"
metadata:
  name: "cartwire-bin-app"
  namespace: "default"
  labels:
    app: "cartwire-bin-app"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "cartwire-bin-app"
  template:
    metadata:
      labels:
        app: "cartwire-bin-app"
    spec:
      containers:
      - name: "cartwire-bin-app"
        image: "gcr.io/exploring-gcp-373314/github_devashish-s_cartwire-bin:latest"
        imagePullPolicy: Always