apiVersion: v1
kind: Secret
metadata:
  name: mysecret
type: Opaque
data:
  password: $(echo -n "secretpassword" | base64)
---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "cartwirebinapp"
  namespace: "default"
  labels:
    app: "cartwirebinapp"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "cartwirebinapp"
  template:
    metadata:
      labels:
        app: "cartwirebinapp"
    spec:
      containers:
      - name: "cartwirebinapp"
        image: "gcr.io/exploring-gcp-373314/github_devashish-s_cartwire-bin:latest"
        imagePullPolicy: Always
        env:
        - name: SECRET_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysecret
              key: password