
---

apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "cartwirebinapp"
  namespace: "default"
  labels:
    app: "cartwirebinapp"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "cartwirebinapp"
  template:
    metadata:
      labels:
        app: "cartwirebinapp"
    spec:
      containers:
      - name: "cartwirebinapp"
        image: "gcr.io/exploring-gcp-373314/github_devashish-s_cartwire-bin:latest"
        imagePullPolicy: Always
        env:
        - name: BERGLAS_SECRET
          value: $(gcloud secrets versions access latest --secret="CARTWIRE_BIN_PROD_DATABASE" --project="exploring-gcp-373314")
---
apiVersion: v1
kind: Pod
metadata:
  name: cartwirebinapp
spec:
  serviceAccountName: my-service-account
  containers:
  - name: "cartwirebinapp"
    image: "gcr.io/exploring-gcp-373314/github_devashish-s_cartwire-bin:latest"
  secrets:
  - name: google-service-account
